name: four_pictures_one_word
description: An attempt at recreating the app "4 pictures 1 word" in flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1 
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
